<?php

namespace AppBundle\Repository;

use AppBundle\Helpers\PaginationHelper;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * OrdersRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    public function queryLatest($routeParams = [])
    {
        $qb = $this->createQueryBuilder('o');
        $qb
            ->distinct(true)
            ->innerJoin('o.orderItems', 'order_items')
            ->addSelect('order_items')
            ->innerJoin('order_items.pizza', 'pizza')
            ->addSelect('pizza')
            ->innerJoin('o.shippingAddress', 'shipping_address')
            ->addSelect('shipping_address')
            ->innerJoin('o.customer', 'customer')
            ->addSelect('customer');

        return $qb->getQuery();
    }

    public function findLatest(PaginationHelper $pagination)
    {
        $routeParams = $pagination->getRouteParams();

        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest($routeParams), false));

        $paginator->setMaxPerPage($routeParams['num_items']);
        $paginator->setCurrentPage($routeParams['page']);

        return $paginator;
    }
}
