<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PizzaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PizzaRepository extends EntityRepository
{
    public function findByCategoryId($catId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.category', 'c')
            ->addSelect('c')
            ->where('c.id = :cid')->setParameter('cid', $catId)
            ->getQuery()
            ->getResult();
    }
}
