# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.botman:
        class: AppBundle\Bot\Botman
        arguments:
            - '%fb_token%'
            - '%fb_secret%'
            - '%fb_verification%'
            - '%conversation_cache_time%'
            - '%kernel.project_dir%/storage'

    app.user.canonicalizer.subscriber:
        class: AppBundle\EventListener\CanonicalizerSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    app.helper.address:
        class: AppBundle\Helpers\AddressHelper
        arguments: ['@validator', '@translator']

    app.helper.pagination:
        class: AppBundle\Helpers\PaginationHelper
        autowire: true
