# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.botman:
        class: AppBundle\Bot\Botman
        arguments: ['%fb_token%', '%fb_secret%', '%fb_verification%']

    app.user.canonicalizer.subscriber:
        class: AppBundle\EventListener\CanonicalizerSubscriber
        tags:
            - { name: doctrine.event_subscriber }
